import Head from 'next/head';
import Hero from '../components/home/Hero';
import { FullBox } from '../components/componentStyle/fullBox';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

  const bannerButtonHandler = () => {
    router.push('/coffee-store');
  };
  return (
    <FullBox
      variant={'container'}
      flex={1}
      flexDir={'column'}
      backgroundColor={'#F8E4D0'}
      p={0}
    >
      <Head>
        <title>Coffee Connoiseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero buttonHandler={bannerButtonHandler} />
    </FullBox>
  );
}
